### PR TITLE
Events: initial draft

### PR DESCRIPTION
**Pull request by chcokr**
Initial implementation of events, to be used as in `require('stilr/events')`. Inspired by the problem I mentioned in #18.

### CODE REVIEW

**Comment by chcokr** [comment]
Now that I think about it again, it is not a good idea to implement events-specific logic inside a separate file `stilr/events`. I came to this conclusion because:

Imagine there is another library (e.g. chcokr/stilr-classnames) that calls `#create()` from the `stilr` file, not the `stilr/events` file. Ideally, an `update` event should fire, but it wouldn't because the library is importing `stilr` instead of `stilr/events`.

**Comment by chcokr** [comment]
Just to add to that thought:

If I were to go with the `stilr/events` approach, I actually would've preferred to go with creating a separate repository called `stilr-events` or something.

The incentive we get by embedding an event system into `#create()` is not negligible, so I decided to go with the `stilr` approach instead of `stilr/events`.

I'm pretty sure the file size doesn't increase that much,

**Comment by serapath** [comment]
Does that mean i get some kind of "data-binding" or "user-input" binding of style updates? (on the css property level)?

**Comment by chcokr** [comment]
@serapath I'm not exactly sure how you mean that. I'll refer you to this line in the PR:

https://github.com/kodyl/stilr/pull/19/files#diff-04c6e90faac2675aa89e2176d2eec7d8R234

**Comment by danieljuhl** [comment]
@chcokr thanks - I'll have a look at it and make some testing. I have one concern about this approach. As I see it, this event emitting and and hot-load only applies to development, and thus I would like to avoid including emmett and when running in production. Have you had any thoughts about this?

**Comment by serapath** [comment]
@chcokr the PR looks interesting, so would the following work?
```js
// BUTTON USAGE
var messageBus       = require('./messageBus.js')
var buttonComponent  = require('button-component')
var specialColorCode = '#a339d2'

var buttonStyle = buttonComponent(document.body, messageBus)

messageBus.on('requestUpdates', function () {
  messageBus.emit('newUpdates', {
    data: prompt('What is the new data?')
  })
  buttonStyle.create({ Info__content: { color: specialColorCode } })
})
```

```js
// BUTTON IMPLEMENTATION
var buttonStyle = require('./buttonStyle')

module.exports = function ButtonComponent (parentDOM, eventBus) {

  parentDOM.innerHTML = '<div class="Info">' +
    'Info: <input class="Info__content" type="text" name="info"><br>' +
    '<button class="Info__button">Refresh</button>' +
    '</div>'

  var Info       = parentDOM.querySelector('.Info')
  var __content  = parentDOM.querySelector('.Info__content')
  var __button   = parentDOM.querySelector('.Info__button')

  __button.addEventListener('click',  function onclick (event) {
    // check for updates
    Info.setAttribute('class', 'Info Info--loading')
    eventBus.emit('requestUpdates')
  })

  eventBus.on('newUpdates', function (update) {
    Info.setAttribute('class', 'Info')
    if (update && update.data) {
      __content.value = update.data
    }
  })

  buttonStyle.on('update', function () {
    var newCSS = buttonStyle.render()
    console.log(newCSS)
  })
  return buttonStyle
}
```

**Comment by serapath** [comment]
Regarding user interaction induced styling updates...
**For example:**
* font  color of a chat app changes according to the current mood of the language being used. 
* background color is controlled by a light sensor of the user device
* ...

1. So in general, instead of having `"styling state classes"` (like: "--disabled", "--active", "--large", "--invisible", ...) the styling changes more fluent based on continuous user input (e.g. `mouse movement`)
2. There might be some constraints, (e.g. text color should always be the same as border color)...

In the example above, the `ButtonComponent` returns access to `buttonStyle`, which can be updated by the parent or if published globally, then by any other component. In a "real world scenario", i might have not written the buttonComponent myself, so it would be great to have some kind of `Styling API`, that tells me what styles I can manipulate or overwrite and takes care that constraints will hold (e.g. text color === border color)

**How to realize runtime styling updates?**

**Comment by chcokr** [comment]
@serapath 

I'm going to sum up and think that what you're asking is:
> how to realize runtime styling updates.

Over the past couple of months, I have figured out enough engineering to realize what you want, using Stillr - in both dev and prod environments. I'm in the middle of preparing a few libraries to make this dream happen, along with a comprehensive blog post. I plan to get a rough draft of everything out by this Sunday. You'll want to check the blog post out - I'll keep you updated.

@danieljuhl

1) 

I actually think some people might end up using the events feature in production environment as well. The concern I explained in #18 is a valid one in prod environment as well, and people can choose to use the events feature in prod to resolve the problem, even in prod env. So I think the events feature should be enabled even in prod env.

Remember, what I want is to attach an event to `#create()`. If we're not consistent about triggering this event, things will break. I strongly suggest that we leave the events feature in prod.

If file size is a concern, maybe I could replace `emmett` with some other minimal `EventEmitter` library.

2)

>  I'll have a look at it and make some testing

I already added one test, and I don't think there needs to be much testing done outside that one test. Could you give me an ETA on when you'll finish reviewing my PR? I'd love to see this PR merged within this week.

**Comment by serapath** [comment]
@chcokr sounds great :-)
I checked the following modules:
* https://github.com/jsstyles/jss
* https://github.com/pygy/j2c
* https://github.com/kodyl/stilr
* https://github.com/hackhat/smart-css
and the only one with the feature to update existing styling seems to be `jss`, so i'm currently using it, but it seems `jss` might offer more than i need, even though i can't say for sure yet :-)

**Comment by danieljuhl** [comment]
@chcokr I'm still trying to figure out, if this pull request has value to Stilr. The idea is to create a StyleSheet once, and extract it all, either in the build process or during server-side rendering.

For hot loading during development, I can see a use case - but to be honest, I can't imagine any production use cases. Can you please give me an example?

What is the purpose of manipulating the `StyleSheet` on the fly? Couldn't you simply assign those minor changes (your example with a chat app, where the color of text and border could change) to the components/elements as inline-styles?

**Comment by serapath** [comment]
yes, they can be assigned as inline-styles.
Heavy usage of that kind of changes will make heavy use of inline styles and i need to "manage" those, eventually writing my own "stilr" similar library, which is why I was asking for that feature.

I imagine css stylesheets will contain only some kind of "default" styles which will change through user interaction later on.

**Comment by chcokr** [comment]
@danieljuhl  Thanks for your comments. After giving this a lot of thought, I've come to the conclusion that I agree with you: the only use case I can think of has been reduced down to hot-loading. I did have a potential use case for production, but after better understanding Stilr, I realized that the production use case could be achieved in other manners.

As for hot-loading, do you agree with what I'm saying in #18?

If so, I wish we could move in a direction where the events feature will not be included in production environment. But this is tricky, because everyone identifies prod environments differently. Some do it with `process.env.NODE_ENV`, some do it with `ENVIRONMENT`, etc. I'm not sure what needs to happen in this regard.

If there are any other ways to work around #18, please let me know - if so, this PR doesn't need to happen.

**Comment by chcokr** [comment]
I've come up with a better idea to work around #18. I'm going to submit a new PR soon and am closing this one.

**Comment by chcokr** [comment]
Nevermind, I thought I had a better idea but I actually didn't.

So let me sum up the problem discussed so far.

As stated in #18, the `EventEmitter` idea is crucial for hot-loading to work across a big app (unless @danieljuhl has a better idea of how to do it). But in production, there's no good use case for the events feature.

Thus, what needs to happen is to provide the user with an option to exclude `emmett`. But this is a bit tricky because everyone defines production differently: some use `production.env`, some use `production.env.NODE_ENV`, etc...

So I propose that we define *our own new environment variable*, called `process.env.STILR_EVENTS`. I will add in code such that unless this variable is truthy, `require('emmett')` will never be called and thus there's no need to worry about a bigger file size. I propose in addition that, when this variable is not truthy, the `#on()` and `#off()` methods will throw an `Error` warning they are not available without the variable set.

I believe this is good compromise among all the problems we've run into so far. A new commit to this PR coming soon.

**Comment by chcokr** [comment]
I will also switch out `emmett` with [event-emitter](https://github.com/medikoo/event-emitter/blob/master/index.js), which is *tiny* (it's only 109 sloc unminified).

Honestly, if @danieljuhl didn't oppose, I wouldn't even bother with `process.env.STILR_EVENTS` and just include `event-emitter` in all cases, because the additional file size is so trivial. But it seems like I have to make a compromise here.

**Comment by chcokr** [comment]
Actually, now that I look at things again, I don't think `event-emitter` is smaller than `emmett` - I overlooked `event-emitter`'s dependencies.

I mean, `emmett` is only 3KB minified before gzip. But if @danieljuhl still wants to exclude `emmett` in production, `process.env.STILR_EVENTS` seems like the way to go.

**Comment by chcokr** [comment]
I'm back. Over the past few days, I ended up concluding that there is indeed a better way to do hot-loading all across the app. My efforts culminated to babel-plugin-stilr-classnames. I hope you check it out. I no longer need this PR - closing it.

**Pull request closed without merging**
